name: Run pytest Mitosheet tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'

jobs:
  test-mitosheet-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        pandas-version: ['0.24.2', '1.1.5', '1.3.5']
        exclude:
          - python-version: 3.6
            pandas-version: '1.3.5'
          - python-version: 3.7
            pandas-version: '1.3.5'
          - python-version: 3.8
            pandas-version: '0.24.2'

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd mitosheet
        python -m pip install --upgrade pip
        pip install "pandas==${{ matrix.pandas-version }}"
        pip install -e ".[test, deploy]"
    - name: Lint with flake8
      run: |
        cd mitosheet
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd mitosheet
        pytest
